### ISSUE TITLE
Failed to set value in the registry

### ISSUE THREAD

**Issue by dernerl** [TheTechBeast8/HardeningAudit#2]
Hello,
first of all thanks for this work. I think this will help a lot. Unfortunately I'm getting errors when the scripts tries to set registry keys.
![image](https://github.com/user-attachments/assets/20e2e3e1-1754-4afa-a3de-456a4e12ed15)

**Comment by dernerl** [comment]
I manually tried to set registry vaules and I think I got the solution
![image](https://github.com/user-attachments/assets/a16f366b-9ad1-4583-a8dc-7ee7dd6adfd0)

Is it the path? -Path HKLM**:**\SOFTWARE

**Comment by TheTechBeast8** [comment]
I did do some quick testing with these and I see it has broken. I swear it worked when I uploaded it as part of my initial upload but I must have bashed some changes and reverted to a previous version that doesn't work. I will look into this.

**Comment by TheTechBeast8** [comment]
I work during the day so just know I will get back to you usually after I get off.

**Comment by TheTechBeast8** [comment]
@dernerl I uploaded the new files. Please try them and let me know. My testing seems to have worked.

**Comment by dernerl** [comment]
yes, now it works. Thanks again!
